# Generated by Django 5.0.6 on 2024-11-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagennoticia',
            old_name='imagen_url',
            new_name='imagen',
        ),
    ]
