# Generated by Django 5.0.6 on 2024-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240904_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
